### ISSUE TITLE
(Likely Bug) Character window & Change or Fetch skills broken in Mac binaries

### ISSUE THREAD

**Issue by zanglebert** [DarkFenX/Pyfa#394]
Latest Mac build (binaries).

* [x] Open character window => Not able to close it again, i.e. pressing "Ok" doesn't do anything

* [x] Cannot fetch skills via API => empty error message

* [ ] Cannot save manually changed skills => probably due to (1) above

**Comment by dachucky** [comment]
Haven't tested 2 or 3, but I had the first issue. Latest build (1.16.0) for Windows installed via the Windows installer.

An additional bit of behaviour I've noticed: The Character Editor correctly acts as a modal window until the first time you attempt to close it. At that point, it just acts like another window that stays on top. You can also open additional character editor windows once you have tried to close the existing one.

**Comment by dachucky** [comment]
Traceback when running from source:
```
Traceback (most recent call last):
  File "D:\Projects\pyfa\gui\characterEditor.py", line 203, in closeEvent
    wx.PostEvent(self.mainFrame, GE.CharListUpdated())
AttributeError: 'CharacterEditor' object has no attribute 'mainFrame'
```

**Comment by ultratwo** [comment]
This appears to be caused by c436e0e669bc16fa59defa848d0a40d9edcc6880 which removes the line

    self.mainFrame = parent

from ``gui/characterEditor.py`` in addition some other lines which the author intended to remove.

This appears to be a trivial mistake that prevents the character editor window from closing (due to causing the above error). Reinserting said line resolves the issue for me (on Linux).

**Comment by blitzmann** [comment]
Aye, that was a mistake. I put the override toggle in the character editor during development and seemed to have removed the mainframe pointer by mistake. This should be fixed in the repo.
